/* Generated by AN DISI Unibo */ 
package it.unibo.sistemas

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sistemas ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
			   fun eval(x: Double): String{
			   	 val R = 3*x
			   	 return ""+R
			   }	
			   
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("sistemas | init")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitMsg", cond=doswitch() )
				}	 
				state("waitMsg") { //this:State
					action { //it:State
						CommUtils.outcyan("sistemas | waiting for msg")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleEval",cond=whenDispatch("eval"))
					transition(edgeName="t01",targetState="handleReq",cond=whenRequest("evalr"))
				}	 
				state("handleEval") { //this:State
					action { //it:State
						CommUtils.outcyan("$name | msg=$currentMsg")
						if( checkMsgContent( Term.createTerm("arg(V)"), Term.createTerm("arg(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
											  val VString = payloadArg(0)
											  val V = VString.toDouble()
											  val R = eval(V)	
								CommUtils.outcyan("sistemas | result = $R")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitMsg", cond=doswitch() )
				}	 
				state("handleReq") { //this:State
					action { //it:State
						CommUtils.outcyan("$name | msg=$currentMsg")
						 var R = ""  
						if( checkMsgContent( Term.createTerm("argr(V)"), Term.createTerm("argr(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
											  val VString = payloadArg(0)
											  val V = VString.toDouble()
											  R = eval(V)	
								CommUtils.outcyan("sistemas | result = $R")
						}
						answer("evalr", "ereplay", "value($R)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitMsg", cond=doswitch() )
				}	 
			}
		}
} 
