/* Generated by AN DISI Unibo */ 
package it.unibo.firefly

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Firefly ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=true ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		  
				    var Timer = 500L
		    		var X = 1
		    		var Y = 1
		    		var ON = 1
		    		var OFF = 0
		    		
		    		fun setCellCoords( )  {
		     		  val coordY = name.replace("firefly_","")    
		      		  Y  = coordY.toInt()     
		  		    }		
		    			
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						 setCellCoords()                                     
						 Timer = java.util.Random().nextLong(1000L,2000L )   
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						observeResource("localhost","8040","ctxfirefly","firefly_queen","synch")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="flash", cond=doswitch() )
				}	 
				state("flash") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | turnOn $Timer")
						forward("cellstate", "cellstate($X,$Y,$ON)" ,"griddisplay" ) 
						delay(Timer)
						CommUtils.outcyan("$name | turnOff $Timer")
						forward("cellstate", "cellstate($X,$Y,$OFF)" ,"griddisplay" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_flash", 
				 	 					  scope, context!!, "local_tout_"+name+"_flash", Timer )  //OCT2023
					}	 	 
					 transition(edgeName="t01",targetState="flash",cond=whenTimeout("local_tout_"+name+"_flash"))   
					transition(edgeName="t02",targetState="newtimer",cond=whenDispatch("synch"))
				}	 
				state("newtimer") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("changed(SOURCE,TIME)"), Term.createTerm("changed(SOURCE,TIME)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								            val t = payloadArg(1)
								            Timer = t.toLong()
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="flash", cond=doswitch() )
				}	 
			}
		}
} 
