/* Generated by AN DISI Unibo */ 
package it.unibo.sonar_mock

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sonar_mock ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		  
				    var Timer = 1000L
		    		var DMIN = 100
		    		var SYNCH = 0
		    		var D = 500
		    			
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="eval", cond=doswitch() )
				}	 
				state("eval") { //this:State
					action { //it:State
						delay(5000) 
						 D = java.util.Random().nextInt(10, 150)  
						CommUtils.outyellow("$name | new distance: $D")
						if(  D < DMIN  
						 ){ SYNCH = 1  
						CommUtils.outyellow("$name | SYNCH")
						updateResourceRep( "$name,$SYNCH,$Timer"  
						)
						}
						else
						 { SYNCH = 0  
						 CommUtils.outyellow("$name | FREE")
						 updateResourceRep( "$name,$SYNCH,$Timer"  
						 )
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="eval", cond=doswitch() )
				}	 
			}
		}
} 
